language: ruby
before_script: "bundle exec rake appraisal:install"
rvm:
  - jruby-18mode
  - jruby-19mode
gemfile:
  - Gemfile
  - gemfiles/rails23.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
branches:
  only:
    - master
