language: ruby
sudo: false
bundler_args: --without development
script: bundle exec rake test_$DB
before_script:
  - export JRUBY_OPTS="--server $JRUBY_OPTS" # -Xcompile.invokedynamic=false
  - mvn prepare-package # compiles ext generates: lib/arjdbc/jdbc/adapter_java.jar
  - mysql --version || true # to see if we're using MySQL or MariaDB
  - '[ "$DB" == "postgresql" ] && rake db:postgresql || true'
  - '[ "$DB" == "mysql" ] && rake db:mysql || true'
  - '[ "$DB" == "mariadb" ] && rake db:mysql || true'
  - '[ "$DB" == "jdbc" ] && rake db:mysql || true'
  - '[ "$DB" == "jndi" ] && rake db:mysql || true'
rvm:
  - jruby-1.7.26
jdk:
  - openjdk7 # we target Java 6+ yet do have Java 7 java.sql APIs (thus needed to compile)
gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
env:
  - JRUBY_OPTS="$JRUBY_OPTS" DB=mysql
  - JRUBY_OPTS="--2.0 $JRUBY_OPTS" DB=mysql PREPARED_STATEMENTS=false
  - JRUBY_OPTS="$JRUBY_OPTS" DB=mysql PREPARED_STATEMENTS=true
  - JRUBY_OPTS="$JRUBY_OPTS" DB=mariadb PREPARED_STATEMENTS=false
  - JRUBY_OPTS="$JRUBY_OPTS" DB=postgresql
  - JRUBY_OPTS="$JRUBY_OPTS" DB=postgresql PREPARED_STATEMENTS=false INSERT_RETURNING=true
  - JRUBY_OPTS="--2.0 $JRUBY_OPTS" DB=postgresql PREPARED_STATEMENTS=true
  - JRUBY_OPTS="$JRUBY_OPTS" DB=postgresql PREPARED_STATEMENTS=true INSERT_RETURNING=true
  - JRUBY_OPTS="$JRUBY_OPTS" DB=sqlite3
  - JRUBY_OPTS="$JRUBY_OPTS" DB=derby
  - JRUBY_OPTS="$JRUBY_OPTS" DB=derby PREPARED_STATEMENTS=true
  - JRUBY_OPTS="$JRUBY_OPTS" DB=h2
  - JRUBY_OPTS="$JRUBY_OPTS" DB=h2 PREPARED_STATEMENTS=true
  - JRUBY_OPTS="$JRUBY_OPTS" DB=hsqldb
  - JRUBY_OPTS="--2.0 $JRUBY_OPTS" DB=hsqldb PREPARED_STATEMENTS=true
  - JRUBY_OPTS="$JRUBY_OPTS" DB=jndi
  - JRUBY_OPTS="$JRUBY_OPTS" DB=jndi PREPARED_STATEMENTS=true
  - JRUBY_OPTS="$JRUBY_OPTS" DB=jdbc
  - JRUBY_OPTS="$JRUBY_OPTS" DB=jdbc PREPARED_STATEMENTS=true
branches:
  only:
    - master
    - /.*-stable$/
    - /^test-.*/
    - /maintenance|support/
    - /.*dev$/
matrix:
  allow_failures:
    #- rvm: jruby-head
    - gemfile: gemfiles/rails42.gemfile
    # these fail on 9K (JNDI bind/lookup issue) ... since ~ pre2 :
    - env: JRUBY_OPTS="$JRUBY_OPTS" DB=jndi
    - env: JRUBY_OPTS="$JRUBY_OPTS" DB=jndi PREPARED_STATEMENTS=true
    - env: DB=mariadb
    - env: DB=mariadb PREPARED_STATEMENTS=true
  include: # testing against MariaDB
    - addons:
        mariadb: '5.5'
      rvm: jruby-1.7.26
      gemfile: gemfiles/rails32.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=mysql
      jdk: openjdk6
    - addons:
        mariadb: '10.1'
      rvm: jruby-1.7.26
      gemfile: gemfiles/rails42.gemfile
      env: DB=mariadb
      jdk: openjdk7
    - addons:
        mariadb: '10.1'
      rvm: jruby-1.7.26
      gemfile: gemfiles/rails41.gemfile
      env: DB=mariadb PREPARED_STATEMENTS=true
      jdk: oraclejdk8
      # include some tests on JDK 6 :
#    - rvm: jruby-1.7.26
#      gemfile: gemfiles/rails42.gemfile
#      env: JRUBY_OPTS="$JRUBY_OPTS" DB=mysql
#      jdk: openjdk6
#    - rvm: jruby-1.7.26
#      gemfile: gemfiles/rails42.gemfile
#      env: JRUBY_OPTS="$JRUBY_OPTS" DB=postgresql
#      jdk: openjdk6
#    - rvm: jruby-1.7.26
#      gemfile: gemfiles/rails42.gemfile
#      env: JRUBY_OPTS="$JRUBY_OPTS" DB=sqlite3
#      jdk: openjdk6
#    - rvm: jruby-1.7.26
#      gemfile: gemfiles/rails42.gemfile
#      env: JRUBY_OPTS="$JRUBY_OPTS" DB=derby
#      jdk: openjdk6
#    - rvm: jruby-1.7.26
#      gemfile: gemfiles/rails42.gemfile
#      env: JRUBY_OPTS="$JRUBY_OPTS" DB=h2
#      jdk: openjdk6
#    - rvm: jruby-1.7.26
#      gemfile: gemfiles/rails42.gemfile
#      env: JRUBY_OPTS="$JRUBY_OPTS" DB=hsqldb
#      jdk: openjdk6
      # include testing with JRuby 9K (4.2) :
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=mysql PREPARED_STATEMENTS=true
      jdk: oraclejdk7
    - rvm: jruby-9.1.6.0
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=postgresql PREPARED_STATEMENTS=true
      jdk: oraclejdk7
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=sqlite3
      jdk: oraclejdk7
    - rvm: jruby-9.1.6.0
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=mysql
      jdk: oraclejdk8
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=postgresql
      jdk: oraclejdk8
    - rvm: jruby-9.1.6.0
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=sqlite3
      jdk: oraclejdk8
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=derby
      jdk: oraclejdk8
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=h2
      jdk: oraclejdk8
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails42.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=hsqldb
      jdk: oraclejdk8
      # include testing with JRuby 9K (4.1) :
    - rvm: jruby-9.0.5.0
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=mysql PREPARED_STATEMENTS=true
      jdk: oraclejdk8
    - rvm: jruby-9.0.5.0
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=postgresql PREPARED_STATEMENTS=true
      jdk: oraclejdk8
    - rvm: jruby-9.0.5.0
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=sqlite3
      jdk: oraclejdk8
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=mysql
      jdk: oraclejdk7
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=postgresql
      jdk: oraclejdk7
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=sqlite3
      jdk: oraclejdk8
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=derby
      jdk: oraclejdk7
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=h2
      jdk: oraclejdk7
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=hsqldb
      jdk: oraclejdk8