language: ruby
sudo: false
bundler_args: --without development
script:
  - bundle exec rake test_$DB
  - bundle exec rake rails:test:$DB
before_script:
  - export JRUBY_OPTS="--server $JRUBY_OPTS" # -Xcompile.invokedynamic=false
  - mysql --version # to see if we're using MySQL or MariaDB
rvm:
  - jruby-9.1.14.0
jdk:
  - openjdk8
env:
  - DB=mysql PREPARED_STATEMENTS=false
  - DB=mysql PREPARED_STATEMENTS=true
  - DB=postgresql PREPARED_STATEMENTS=false INSERT_RETURNING=false
  - DB=postgresql PREPARED_STATEMENTS=false INSERT_RETURNING=true
  - DB=postgresql PREPARED_STATEMENTS=true
  - DB=postgresql PREPARED_STATEMENTS=true INSERT_RETURNING=true
  - DB=sqlite3 PREPARED_STATEMENTS=false
  - DB=sqlite3 PREPARED_STATEMENTS=true
  #- DB=derby PREPARED_STATEMENTS=false
  #- DB=derby PREPARED_STATEMENTS=true
  #- DB=h2
  #- DB=h2 PREPARED_STATEMENTS=true
  #- DB=hsqldb
  #- DB=hsqldb PREPARED_STATEMENTS=true
  - DB=jndi PREPARED_STATEMENTS=false
  - DB=jndi PREPARED_STATEMENTS=true
  #- DB=jdbc
  #- DB=jdbc PREPARED_STATEMENTS=true
branches:
  only:
    - master
    - /.*-stable$/
    - /^test-.*/
matrix:
  include:
    # testing against MariaDB
    - addons:
        mariadb: '10.0'
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=mariadb PREPARED_STATEMENTS=false
    - addons:
        mariadb: '10.0'
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=mariadb PREPARED_STATEMENTS=true
