language: ruby
sudo: false
bundler_args: --without development
script: bundle exec rake test_$DB
before_script:
  - export JRUBY_OPTS="--dev $JRUBY_OPTS" # -Xcompile.invokedynamic=false
  - mysql --version # to see if we're using MySQL or MariaDB
before_install:
  - ((jruby -v | grep 1.8.7) && jruby --1.9 -S gem update --system 2.1.11) || true
rvm:
  - jruby-18mode
  - jruby-19mode
  #- jruby-head
jdk:
  - openjdk6
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails23.gemfile
env:
  - DB=mysql
  - DB=mysql PREPARED_STATEMENTS=true
  - DB=postgresql
  - DB=postgresql PREPARED_STATEMENTS=false INSERT_RETURNING=true
  - DB=postgresql PREPARED_STATEMENTS=true
  - DB=postgresql PREPARED_STATEMENTS=true INSERT_RETURNING=true
  - DB=sqlite3
  - DB=sqlite3 PREPARED_STATEMENTS=true
  - DB=derby
  - DB=derby PREPARED_STATEMENTS=true
  - DB=h2
  - DB=h2 PREPARED_STATEMENTS=true
  - DB=hsqldb
  - DB=hsqldb PREPARED_STATEMENTS=true
  - DB=jndi
  - DB=jndi PREPARED_STATEMENTS=true
  - DB=jdbc
  - DB=jdbc PREPARED_STATEMENTS=true
branches:
  only:
    - master
    - /.*-stable$/
    - /^test-.*/
matrix:
  allow_failures:
    - rvm: jruby-head
    - env: DB=jdbc
    - env: DB=jdbc PREPARED_STATEMENTS=true
  include: # testing against MariaDB
    - addons:
        mariadb: '5.5'
      rvm: jruby
      gemfile: gemfiles/rails32.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=mysql
      jdk: openjdk7
    - addons:
        mariadb: '10.0'
      rvm: jruby
      gemfile: gemfiles/rails40.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=mariadb
      jdk: openjdk7
    - addons:
        mariadb: '10.0'
      rvm: jruby
      gemfile: gemfiles/rails41.gemfile
      env: JRUBY_OPTS="$JRUBY_OPTS" DB=mariadb PREPARED_STATEMENTS=true
      jdk: openjdk7
  exclude:
    # Rails 4 prefers Ruby 2.0 (or at least >= 1.9.3) :
    - rvm: jruby-18mode
      gemfile: gemfiles/rails40.gemfile
    # Rails 4.1 does not support Ruby 1.8 :
    - rvm: jruby-18mode
      gemfile: gemfiles/rails41.gemfile
    # Rails 4.2 will not support Ruby 1.8 :
    - rvm: jruby-18mode
      gemfile: gemfiles/rails42.gemfile
    ## JRuby 9K :
    # Rails 2.3 (JRuby 9K)
    - rvm: jruby-head
      gemfile: gemfiles/rails23.gemfile
    # Rails 3.0 (JRuby 9K)
    - rvm: jruby-head
      gemfile: gemfiles/rails30.gemfile
    # Rails 3.1 (JRuby 9K)
    - rvm: jruby-head
      gemfile: gemfiles/rails31.gemfile
    # Rails 3.2 (JRuby 9K)
    - rvm: jruby-head
      gemfile: gemfiles/rails32.gemfile
    # Rails 4.0 (JRuby 9K)
    - rvm: jruby-head
      gemfile: gemfiles/rails40.gemfile
    # Rails 4.1 (JRuby 9K)
    - rvm: jruby-head
      gemfile: gemfiles/rails41.gemfile
    # Rails 4.2 (JRuby 9K)
    - rvm: jruby-head
      gemfile: gemfiles/rails42.gemfile
