language: ruby
sudo: false
bundler_args: --without development
script: bundle exec rake test_$DB
before_script:
  - export JRUBY_OPTS="--server $JRUBY_OPTS" # -Xcompile.invokedynamic=false
  #- mvn prepare-package # compiles ext generates: lib/arjdbc/jdbc/adapter_java.jar
  - mysql --version || true # to see if we're using MySQL or MariaDB
  - '[ "$DB" == "postgresql" ] && rake db:postgresql || true'
  - '[ "$DB" == "mysql" ] && rake db:mysql || true'
  - '[ "$DB" == "mariadb" ] && rake db:mysql || true'
  - '[ "$DB" == "jdbc" ] && rake db:mysql || true'
  - '[ "$DB" == "jndi" ] && rake db:mysql || true'

rvm:
  - jruby-9.1.14.0
jdk:
  - openjdk8
env:
  - DB=mysql PREPARED_STATEMENTS=false
  - DB=mysql PREPARED_STATEMENTS=true
  - DB=postgresql PREPARED_STATEMENTS=false INSERT_RETURNING=false
  - DB=postgresql PREPARED_STATEMENTS=false INSERT_RETURNING=true
  - DB=postgresql PREPARED_STATEMENTS=true
  - DB=postgresql PREPARED_STATEMENTS=true INSERT_RETURNING=true
  - DB=sqlite3 PREPARED_STATEMENTS=false
  - DB=sqlite3 PREPARED_STATEMENTS=true
  #- DB=jndi PREPARED_STATEMENTS=false
  #- DB=jndi PREPARED_STATEMENTS=true
branches:
  only:
    - master
    - /.*-stable$/
    - /^test-.*/
    - /maintenance|support/
    - /.*dev$/
matrix:
  include:
    # testing against MariaDB
    - addons:
        mariadb: '10.0'
      env: DB=mariadb PREPARED_STATEMENTS=false
    - addons:
        mariadb: '10.1'
      env: DB=mariadb PREPARED_STATEMENTS=true
